### ISSUE TITLE
validator_filetype_map not work for me

### ISSUE THREAD

**Issue by francescarpi** [maralla/validator.vim#16]
Hi again,

I have this setting:

```vim
let g:validator_filetype_map = {"python.django": "python", "javascript.jsx": "javascript"}
let g:validator_javascript_checkers = ['eslint']
let g:validator_python_checkers = ['flake8']
let g:validator_error_msg_format = "[ ● %d/%d issues ]"
```

But aliases not work and I not know why.

I'm using *python.django* filetype. This is an example:

```python
#!/usr/bin/env python
# encoding: utf-8
# vim:ft=python.django:
# --------------------------------------------------------------------------

class Example(object):
    pass
```
Can you reproduce it?
Thx

**Comment by maralla** [comment]
<img width="744" alt="screen shot 2016-09-21 at 6 17 40 pm" src="https://cloud.githubusercontent.com/assets/2238118/18707257/d003c7fc-8027-11e6-98df-c103b4ac1fa9.png">

In my environment it works pretty well.

Do you really installed `flake8` and upgraded validator.vim to the latest commit.

**Comment by francescarpi** [comment]
Hi.

Yes. I'have installed *flake8* and *validator.vim* has upgraded to latest version.

Work fine with *python* fieletype, but not with *python.django*.

I'm investigate why...

**Comment by mhinton** [comment]
I have the same issue using these settings.

```
let g:validator_filetype_map = {"javascript.jsx": "javascript"}
let g:validator_javascript_checkers = ['eslint']
let g:validator_auto_open_quickfix = 1
```

**Comment by maralla** [comment]
@francescarpi Could you go to your validator.vim directory and run:
```bash
find . -name "*.pyc" -delete
```
to delete all python caches and try again?

**Comment by francescarpi** [comment]
Hi @maralla,

I'm sorry, but not work. I have deleted pyc.

My versions:
Python 3.5.2
Vim 8.0.7
flake 3.0.4
eslint 3.5.0

Thx!

**Comment by maralla** [comment]
This fix #19 may fix the problem, please upgrade and try again.

**Comment by francescarpi** [comment]
Hi,

still not working. Look at this strange behavior.

![validator](https://cloud.githubusercontent.com/assets/287872/18743795/0ce04928-80bb-11e6-8478-2fbd9276eca3.gif)

Thx!

**Comment by maralla** [comment]
I pushed one more [commit](https://github.com/maralla/validator.vim/commit/39494dddf0d785db86f9cf8ba043379b06fc032f) to solve this problem. Can you try it again?

**Comment by francescarpi** [comment]
Yessss!
Its ok, now!!
You are the best!

Thx
