### ISSUE TITLE
Can i disable __validator__temp__ creation?

### ISSUE THREAD

**Issue by minhyeong-kim** [maralla/validator.vim#28]
__validator_temp__.js files are created when using vim.

this file disturb git staging action.

can i disable __validator_temp__ creation or move it's to other directory?

**Comment by maralla** [comment]
This file should be deleted after every check. Some checkers like `eslint` use the file path to find a proper config file. If this kind of temp file created in other directories config files in the per project directory will not be detected.

**Comment by aliev** [comment]
@maralla it is really annoying for git repo, sometimes I do not have time to remove it and it is loaded directly into the repository.

**Comment by sirfz** [comment]
I have this issue when using `vim-fugitive` commands such as `Gdiff` to view the diff between the local and remote files, basically when I run the command I get an error:

```
Error detected while processing function <SNR>85_do_check[2]..<SNR>85_check:                                                                                  
line   41:                                                                                                                                                    
E482: Can't create file fugitive:///<path-to-repo>/.git//0/<path-to-file-dir>/__validator_temp__.py
```

Basically, fugitive is unusable with this plugin. Anyway to disable validator for .git files?

**Comment by aliev** [comment]
@sirfz webpack also returns warnings like this

```
WARNING in ./assets/jsx/__validator_temp__.jsx
Module build failed: Error: ENOENT: no such file or directory, open '/Users/aliev/Projects/the-crimson-bride/assets/jsx/__validator_temp__.jsx'
```

**Comment by everedifice** [comment]
This is really anoying phenomenon for me. git trying to track `__validator_temp__.js` file.

```zsh
➜  project git:(develop) ✗ gst
On branch develop
Your branch is up-to-date with 'origin/develop'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        src/actions/__validator_temp__.js

nothing added to commit but untracked files present (use "git add" to track)
```
