### ISSUE TITLE
Checkers Arguments Support

### ISSUE THREAD

**Issue by sirfz** [maralla/validator.vim#31]
Syntastic supports customization of checkers by passing extra args to them. For example I used to have this setting:

```vim
let g:syntastic_python_flake8_args="--max-line-length=120"
```

This disables pep8 warnings about exceeding the default max line length (80) and trigger on 120 instead.

I imagine this would be useful in other scenarios as well.

**Comment by KabbAmine** [comment]
:+1: 

An option to overwrite/add arguments will be very handful, it will solve for example #35

**Comment by maralla** [comment]
Now you can overwrite the arguments like this:
```vim
let g:validator_option = {
      \    'args': {
      \      'python': {'flake8': '--max-line-length=120'}
      \    }
      \ }
```
