### ISSUE TITLE
Dependence Validator

### ISSUE THREAD

**Issue by simepy** [maralla/validator.vim#58]
Hello,

I try install Validator in NeoVim but I have this error: 
Validator requires vim compiled with python or python3 and has features `job`, `timers` and `lambda`

I have Python and Python3 but What is it: job timers and lambda ? and how add this dependence ?

Thanks

**Comment by renstrom** [comment]
`timers` is already available (at least on master). Neovim has its own `job` thingie, which isn't compatible with Vim. And `lambda` is on the way[1].

So unfortunately validator.vim only works with vanilla Vim 8. Meanwhile, I suggest you have a look at https://github.com/w0rp/ale.

[1] https://github.com/neovim/neovim/pull/5771

**Comment by simepy** [comment]
Thank you 👍 !
