### ISSUE TITLE
Rubocop support improvements

### ISSUE THREAD

**Issue by lukkor** [maralla/validator.vim#62]
Hi,

Thanks for merging the PR on basic rubocop support.
Here is a list of improvements I'm working on:

- [x] Fix regex to take into account following case: `E:496:  1: unexpected token kEND`
- [x] Add option to rubocop's args to use `.rubocop.yml` file
- [x] Add support for rubocop error class

Feel free to add improvements or work on the list.
I have a last question about linters, is it planned to move linters into dedicated repos?

Thanks for your work, validator.vim is awesome!

**Comment by maralla** [comment]
I think now it's possible to write lints in external repos.

For example to move python lints to an external repo *validator-python*, the repo structure should be:
```
../
validator-python/
|  pythonx/
|  |  validator_python/
|  |  |  __init__.py
|  |  |  pyflakes.py
```

It's also possible to move linters into dedicated file type repos. Just create `pythonx/validator_{filetype}` directory and move linter implementations to the directory.
