### ISSUE TITLE
Add support for go / gometalinter

### ISSUE THREAD

**Issue by blockloop** [maralla/validator.vim#70]
I'm not sure if you intend this project to be strictly a "linter" or a full blown syntax checker, but implementing alecthomas/gometalinter would be ideal for Golang. I see you have implemented Go in completor.vim so maybe it's in the roadmap?

**Comment by maralla** [comment]
Now the `gometalinter` support has been added. Use the the following config to use it:
```vim
let g:validator_go_checkers = ['gometalinter']
```
