### ISSUE TITLE
Significant VimEnter loadtime

### ISSUE THREAD

**Issue by tuyenpm9** [maralla/validator.vim#77]
I have noticed loadtime of this plugin about 100ms, from 30 to 115->120. Is that normal?
` 030.000: VimEnter autocommands`  
`117.000: VimEnter autocommands`

**Comment by maralla** [comment]
I pushed a commit to decrease the load time. Can you please check it again?

**Comment by tuyenpm9** [comment]
It' back to normal now: `033.000: VimEnter autocommands`

Thanks for awesome plugins :)
