### ISSUE TITLE
Help to install rust checker

### ISSUE THREAD

**Issue by tuyenpm9** [maralla/validator.vim#78]
I'm trying to learn Rust but have no idea how to install its checkers.  
From validator's readme `rst, rst2pseudoxml` but  `cargo search rst2pseudoxml` gave me no result

Can someone help me on this?

**Comment by maralla** [comment]
The `rst2pseudoxml` lint is for [`rst`](http://docutils.sourceforge.net/rst.html) files. Now I pushed some commits to add the rust checker. The checker will not check the files instantly but only when the file saved or read. As the checker will run `cargo check` to check the files, so it may be very slow the first time the checker runs if the project never build.

**Comment by tuyenpm9** [comment]
@maralla : Can you tell me how to install `rst2pseudoxml` lint?. I updated and tried to open a file and :w but seem nothing happen, make some error and save but there's no checked errors.

**Comment by maralla** [comment]
`rst2pseudoxml` is **not** a rust lint. Well you can install this lint with the command `pip install docutils`.

**Comment by maralla** [comment]
If you are editing Rust code, you should create a cargo project and the lint will happen.

**Comment by tuyenpm9** [comment]
@maralla : I have noticed other checkers don't work too. Did you disable all checkers by default?

**Comment by maralla** [comment]
Checkers are enabled by default. But you have to install the corresponding checker tool first.

**Comment by tuyenpm9** [comment]
@maralla : weird, I can't trigger :Validator from gvim, plugin is up-to-date. flake8 is also installed.

**Comment by maralla** [comment]
You can set the config `let g:validator_debug = 1` to enable debug. And the log file is located at */path/to/validator.vim/pythonx/validator.log*. After debug is enabled you can check the log file to see if there has something.

**Comment by tuyenpm9** [comment]
Yes, I enabled debug, got empty validator.log file. Is there any known conflicts with ripgrep, fzf plugin?  
I've just installed those recently.

**Comment by maralla** [comment]
Can you please open a python file and type the following command and post the result:
```vim
:py from validator import load_checkers;print(load_checkers('python'))
```

**Comment by tuyenpm9** [comment]
Result:  
```
E370: Could not load library python27.dll
E263: Sorry, this command is disabled, the Python library could not be loaded.
```   
I have only python3 installed on the machine.

**Comment by maralla** [comment]
Run this:
```vim
:py3 from validator import load_checkers;print(load_checkers('python'))
```

**Comment by tuyenpm9** [comment]
Result:  
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'validator'
```

**Comment by maralla** [comment]
So do you really installed and enabled validator.vim?

**Comment by tuyenpm9** [comment]
Yes, I installed validator.vim via native plugin manager and have its folder under `start/`  
I can't find validator.py under it.

**Comment by maralla** [comment]
What is the full path of validator.vim?

**Comment by tuyenpm9** [comment]
@maralla : `C:\Users\YYYY\vimfiles\pack\plugins\start\validator.vim`

**Comment by maralla** [comment]
What is the result of `:py3 import vim;print(vim._get_paths())`?

**Comment by tuyenpm9** [comment]
`['C:\\Users\\YYYY/vimfiles\\python3', 'C:\\Users\\YYYY/vimfiles\\pythonx', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\vimwiki\\python3', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\vimwiki\\pythonx', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\vim-unimpaired\\python3', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\vim-unimpaired\\pythonx', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\vim-surround\\python3', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\vim-surround\\pythonx', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\vim-snippets\\python3', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\vim-snippets\\pythonx', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\vim-rooter\\python3', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\vim-rooter\\pythonx', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\vim-ripgrep\\python3', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\vim-ripgrep\\pythonx', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\vim-repeat\\python3', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\vim-repeat\\pythonx', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\vim-multiple-cursors\\python3', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\vim-multiple-cursors\\pythonx', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\vim-material-theme\\python3', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\vim-material-theme\\pythonx', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\vim-lastplace\\python3', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\vim-lastplace\\pythonx', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\vim-fugitive\\python3', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\vim-fugitive\\pythonx', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\vim-commentary\\python3', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\vim-commentary\\pythonx', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\validator.vim\\python3', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\validator.vim\\pythonx', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\ultisnips\\python3', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\ultisnips\\pythonx', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\tagbar\\python3', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\tagbar\\pythonx', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\supertab\\python3', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\supertab\\pythonx', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\SimpylFold\\python3', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\SimpylFold\\pythonx', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\limelight.vim\\python3', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\limelight.vim\\pythonx', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\goyo.vim\\python3', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\goyo.vim\\pythonx', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\gitv\\python3', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\gitv\\pythonx', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\fzf.vim\\python3', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\fzf.vim\\pythonx', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\fzf\\python3', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\fzf\\pythonx', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\echodoc.vim\\python3', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\echodoc.vim\\pythonx', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\ctrlp.vim\\python3', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\ctrlp.vim\\pythonx', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\completor.vim\\python3', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\completor.vim\\pythonx', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\auto-pairs\\python3', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\auto-pairs\\pythonx', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\auto-ctags.vim\\python3', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\auto-ctags.vim\\pythonx', 'C:\\Program Files\\Vim/vimfiles\\python3', 'C:\\Program Files\\Vim/vimfiles\\pythonx', 'C:\\Program Files\\Vim\\vim80\\python3', 'C:\\Program Files\\Vim\\vim80\\pythonx', 'C:\\Program Files\\Vim/vimfiles/after\\python3', 'C:\\Program Files\\Vim/vimfiles/after\\pythonx', 'C:\\Users\\YYYY/vimfiles/after\\python3', 'C:\\Users\\YYYY/vimfiles/after\\pythonx', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\ultisnips\\after\\python3', 'C:\\Users\\YYYY\\vimfiles\\pack\\plugins\\start\\ultisnips\\after\\pythonx']`

**Comment by maralla** [comment]
So what is the content of the directory `C:\Users\YYYY\vimfiles\pack\plugins\start\validator.vim\pythonx\`?

**Comment by tuyenpm9** [comment]
tree:
```
├───completers
│   ├───common
│   │   └───__pycache__
│   ├───javascript
│   ├───python
│   │   └───__pycache__
│   └───__pycache__
└───completor
    └───__pycache__
```

**Comment by tuyenpm9** [comment]
I uploaded pythonx folder [here](https://drive.google.com/drive/folders/0BzNBUeqn5ZK5N2swLWt1M3pENUk?usp=sharing), so you can have a look.

**Comment by maralla** [comment]
This is the **completor.vim** directory. I think we are talking about **validator.vim**.

**Comment by tuyenpm9** [comment]
Weird, that's the folder of `C:\Users\YYYY\vimfiles\pack\plugins\start\validator.vim\pythonx`, can you have a check? It's named `comple*`

**Comment by maralla** [comment]
Can you please remove validator.vim and install it again?

**Comment by tuyenpm9** [comment]
My mistake, init submodule from `validator` to `completor`  
Back to rust checker, `:lopen` have list of errors, not like flake8 that has expose errors to statusbar in bottom line, I have to open `:lopen` each time I want to check rust's errors.  
Beside that I make some errors but it only shows only one.  
Any suggestions?

**Comment by maralla** [comment]
Rust checker will not check your code instantly. It only triggers when you read or write a file.

**Comment by tuyenpm9** [comment]
Yes, I downloaded a rust project, `pack` for example, load a file from it. I got the same errors for the whole project, tried with `pack` and `ripgrep` plugins, like:
```
src\package.rs|4 col 9 error| [cargo]error[E0432]: unresolved import `libc::termios`
src\package.rs|50 col 9 error| [cargo]error[E0432]: unresolved import `libc::ioctl`
src\package.rs|51 col 9 error| [cargo]error[E0432]: unresolved import `libc::STDOUT_FILENO`
src\package.rs|2 col 14 error| [cargo]error[E0432]: unresolved import `std::os::unix`
```
open other files will get same errors like above, it's just change the name: `task.rs`, ..etc

**Comment by maralla** [comment]
I pushed a commit to fix the problem. Now the lint message is related to the current file.

**Comment by tuyenpm9** [comment]
@maralla : Please follow this video for full details about this issue [here](https://drive.google.com/file/d/0BzNBUeqn5ZK5MzNuX25rQl9IRzA/view?usp=sharing)  
What do you think?

**Comment by maralla** [comment]
This lint runs `cargo check` to check your rust files. But `cargo check` runs very very slow so the result not shown early enough. Currently the Rust tooling is not very mature, so the experience is not very good.

**Comment by tuyenpm9** [comment]
@maralla : Thanks, hope it will be improve soon.
