### ISSUE TITLE
[Question] How to customize flake's message colors

### ISSUE THREAD

**Issue by tuyenpm9** [maralla/validator.vim#79]
I disable sign column, so it's kind of hard to distinguish between warning and error in status bar when flake8 produce errors/warnings. like [this](https://imgur.com/a/PssAV).   
I know it's not relevant to validator but maybe someone can help me.

**Comment by maralla** [comment]
I pushed a commit to make it possible to highlight lint messages. Set the following config to enable it:
```vim
let g:validator_highlight_message = 1
```
