### ISSUE TITLE
Invalid argument when used with rust

### ISSUE THREAD

**Issue by tpoliaw** [maralla/validator.vim#80]
This could be a configuration issue rather than a bug but when I open or save a rust file I get an error message saying
```
Error detected while processing function <lambda>3[1]..<SNR>75_do_check[10]..<SNR>75_check:
line 45:
E475: Invalid argument: cwd
```

I don't know enough vimscript to start seeing where this is going wrong but let me know if you need any more information.

I have tried setting `g:validator_debug = 1` but nothing is written to the log.

Removing this plugin prevents the error appearing so I'm fairly confident it's from this plugin although I'm happy to believe it's a different one interfering with it somehow.

**Comment by facingBackwards** [comment]
I've been looking at this again and it seems to be conflicting with `rust-lang/rust.vim`. With an empty vimrc apart from those two (using vim-plug), removing either stops the problem, but together causes the bug.

**Comment by maralla** [comment]
Please update vim to the latest version.

**Comment by tpoliaw** [comment]
No longer an issue
