### ISSUE TITLE
Filetype python.django

### ISSUE THREAD

**Issue by francescarpi** [maralla/validator.vim#9]
Hi,

I'm working with _python.django_ filetype.

How can I configure the checker? Because I can not do this...

`let g:validator_python.django_checkers = ['flake8']
`

Thanks!

**Comment by mhinton** [comment]
Filetypes of this format don't currently work. I just discovered this javascript.jsx.

**Comment by maralla** [comment]
@francescarpi Could you please give me an example or a link of a file with `python.django` filetype? I'm not familiar with this kind of type.

**Comment by francescarpi** [comment]
Yes, of course.

Really its same as python filetype.

```python
#!/usr/bin/env python
# encoding: utf-8
# vim:ft=python.django:
# --------------------------------------------------------------------------

class Example(object):
    pass
```

Thx

**Comment by francescarpi** [comment]
I sent to you this pull request (https://github.com/maralla/validator.vim/pull/13)

Plese, check if my implementation is correct.

Thx.

**Comment by maralla** [comment]
This is a much better solution: #14

**Comment by maralla** [comment]
Now you can add this option to support this type:
```vim
let g:validator_filetype_map = {"python.django": "python"}
```
